### ISSUE TITLE
new arabmovies plugin

### ISSUE THREAD

**Issue by emadmahdi** [hmemar/husham.com#6]
Hello ... I fixed arabmovies plugin and i have it fully working and faster than before ... i would like to publish it online ... so do you mind if i publish it with a new name such as arabmovies2018 ... or you can give me authorization so i can publish it to your github repository directly ... please let me know as soon as possible ... Thanks

**Comment by emadmahdi** [comment]
I also added some new features ... such as "watched" status ... and HD/SD stream selection ... and faster response ... also fixed the search and cleaned/optimized the code ...

**Comment by dahulk619** [comment]
What’s that? You can’t use your own? How you get my email?

**Comment by emadmahdi** [comment]
yes ... i can change the name totally but i respect your work ... plus i can't find a good icon for my own plugin ... I am good in graphics but i hate designing icons ... plus your plugin is not working anyways ... plus if you publish my work in your old plugin then people will get the update automatically because they already have your kodi repository and your kodi plugin ...
